### ISSUE TITLE
Header numbering is not working correctly

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Framework#18]
Header numbering is currently displaying incorrectly (0.0.0 instead of a number as it should). Testing has shown this can be solved in one of two ways:

- Amend section header in metadata to be 'h1' plus move all headers in 41framework.md one level up (so h3 becomes h2 and so on). This fixes the numbering so that it is correct
- Comment out or delete all css that causes this numbering to happen. This code can be found in \sass\partials\_generals.css, line 25 and \_sass\partials\_nav.css, lines 43, 46, and 61.

**Comment by kateefly** [comment]
@kateefly will comment out css and note what it does

**Comment by f8f8ff** [comment]
Addressed with PR #24
